type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Generate Products"
      parameters:
        componentName: "Start"
    
    Generate Products:
      type: "sql-executor"
      transitions:
        success:
        - "Generate Stores"
      parameters:
        componentName: "Generate Products"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        enableVariableResolution: "No"
        sqlScript: |
          -- SQL-based Product Data Generator
          -- Generates realistic product catalog with hierarchical categories
          
          INSERT INTO etl_learning.dim_product
          WITH 
          -- Product catalog structure using VALUES
          product_catalog AS (
              SELECT * FROM (VALUES
                  ('Electronics', 'Smartphones', 'iPhone Pro'),
                  ('Electronics', 'Smartphones', 'Galaxy Ultra'),
                  ('Electronics', 'Smartphones', 'Pixel Plus'),
                  ('Electronics', 'Smartphones', 'OnePlus Nord'),
                  ('Electronics', 'Laptops', 'MacBook Air'),
                  ('Electronics', 'Laptops', 'ThinkPad X1'),
                  ('Electronics', 'Laptops', 'XPS 15'),
                  ('Electronics', 'Laptops', 'Surface Pro'),
                  ('Electronics', 'Tablets', 'iPad Pro'),
                  ('Electronics', 'Tablets', 'Galaxy Tab'),
                  ('Electronics', 'Tablets', 'Surface Go'),
                  ('Electronics', 'Tablets', 'Fire HD'),
                  ('Electronics', 'Audio', 'AirPods'),
                  ('Electronics', 'Audio', 'WH-1000XM5'),
                  ('Electronics', 'Audio', 'Galaxy Buds'),
                  ('Electronics', 'Audio', 'Bose QC'),
                  ('Electronics', 'Wearables', 'Apple Watch'),
                  ('Electronics', 'Wearables', 'Galaxy Watch'),
                  ('Electronics', 'Wearables', 'Fitbit Sense'),
                  ('Electronics', 'Wearables', 'Garmin Venu'),
                  ('Clothing', 'Shirts', 'Oxford Shirt'),
                  ('Clothing', 'Shirts', 'Polo Classic'),
                  ('Clothing', 'Shirts', 'V-Neck Tee'),
                  ('Clothing', 'Shirts', 'Henley Long'),
                  ('Clothing', 'Pants', 'Slim Chinos'),
                  ('Clothing', 'Pants', 'Classic Jeans'),
                  ('Clothing', 'Pants', 'Cargo Pants'),
                  ('Clothing', 'Pants', 'Dress Slacks'),
                  ('Clothing', 'Outerwear', 'Wool Blazer'),
                  ('Clothing', 'Outerwear', 'Puffer Jacket'),
                  ('Clothing', 'Outerwear', 'Trench Coat'),
                  ('Clothing', 'Outerwear', 'Fleece Zip'),
                  ('Clothing', 'Footwear', 'Running Shoes'),
                  ('Clothing', 'Footwear', 'Loafers'),
                  ('Clothing', 'Footwear', 'Boots'),
                  ('Clothing', 'Footwear', 'Sneakers'),
                  ('Home', 'Furniture', 'Ergonomic Chair'),
                  ('Home', 'Furniture', 'Standing Desk'),
                  ('Home', 'Furniture', 'Bookshelf Oak'),
                  ('Home', 'Furniture', 'Sofa Sectional'),
                  ('Home', 'Kitchen', 'Coffee Maker'),
                  ('Home', 'Kitchen', 'Blender Pro'),
                  ('Home', 'Kitchen', 'Air Fryer XL'),
                  ('Home', 'Kitchen', 'Instant Pot'),
                  ('Home', 'Decor', 'Table Lamp'),
                  ('Home', 'Decor', 'Wall Art Set'),
                  ('Home', 'Decor', 'Area Rug'),
                  ('Home', 'Decor', 'Plant Pot'),
                  ('Home', 'Bedding', 'Memory Foam Pillow'),
                  ('Home', 'Bedding', 'Duvet Cover'),
                  ('Home', 'Bedding', 'Sheet Set'),
                  ('Home', 'Bedding', 'Mattress Topper'),
                  ('Sports', 'Fitness', 'Yoga Mat'),
                  ('Sports', 'Fitness', 'Dumbbells Set'),
                  ('Sports', 'Fitness', 'Resistance Bands'),
                  ('Sports', 'Fitness', 'Foam Roller'),
                  ('Sports', 'Outdoor', 'Hiking Boots'),
                  ('Sports', 'Outdoor', 'Camping Tent'),
                  ('Sports', 'Outdoor', 'Backpack 40L'),
                  ('Sports', 'Outdoor', 'Trekking Poles'),
                  ('Sports', 'Team Sports', 'Basketball'),
                  ('Sports', 'Team Sports', 'Soccer Ball'),
                  ('Sports', 'Team Sports', 'Tennis Racket'),
                  ('Sports', 'Team Sports', 'Golf Clubs'),
                  ('Office', 'Supplies', 'Notebook Set'),
                  ('Office', 'Supplies', 'Pen Pack'),
                  ('Office', 'Supplies', 'Desk Organizer'),
                  ('Office', 'Supplies', 'File Folders'),
                  ('Office', 'Technology', 'Wireless Mouse'),
                  ('Office', 'Technology', 'Mechanical Keyboard'),
                  ('Office', 'Technology', 'Monitor Stand'),
                  ('Office', 'Technology', 'Webcam HD'),
                  ('Office', 'Furniture', 'Office Chair'),
                  ('Office', 'Furniture', 'L-Desk'),
                  ('Office', 'Furniture', 'Filing Cabinet'),
                  ('Office', 'Furniture', 'Whiteboard')
              ) AS t(category, subcategory, product_name)
          ),
          brands AS (
              SELECT explode(array(
                  'TechPro', 'StyleCo', 'HomeEssentials', 'FitLife', 'Luxura',
                  'ValueMax', 'PremiumPlus', 'EcoChoice', 'ProSeries', 'BasicLine'
              )) AS brand
          ),
          variations AS (
              SELECT explode(array('', ' 2024', ' Plus', ' Pro', ' Lite', ' XL')) AS variation
          ),
          -- Generate product combinations
          product_base AS (
              SELECT 
                  ROW_NUMBER() OVER (ORDER BY p.category, p.subcategory, p.product_name, v.variation) AS product_id,
                  p.category,
                  p.subcategory,
                  CONCAT(p.product_name, v.variation) AS product_name,
                  p.product_name AS base_name
              FROM product_catalog p
              CROSS JOIN variations v
              WHERE v.variation = '' OR rand() > 0.7
          ),
          -- Limit to 500 products
          limited_products AS (
              SELECT * FROM product_base
              WHERE product_id <= 500
          )
          SELECT 
              product_id,
              CONCAT(UPPER(SUBSTR(category, 1, 3)), '-', 
                     CAST(100 + FLOOR(rand(product_id) * 900) AS INT), '-',
                     LPAD(CAST(product_id AS STRING), 4, '0')) AS product_sku,
              product_name,
              CONCAT('High-quality ', LOWER(base_name), ' in ', LOWER(subcategory), ' category') AS product_description,
              category,
              subcategory,
              (SELECT brand FROM brands ORDER BY rand(product_id) LIMIT 1) AS brand,
              -- Cost based on category
              ROUND(
                  CASE category
                      WHEN 'Electronics' THEN 50 + rand(product_id + 1000) * 450
                      WHEN 'Clothing' THEN 10 + rand(product_id + 1000) * 90
                      WHEN 'Home' THEN 20 + rand(product_id + 1000) * 280
                      WHEN 'Sports' THEN 15 + rand(product_id + 1000) * 135
                      WHEN 'Office' THEN 5 + rand(product_id + 1000) * 95
                      ELSE 20 + rand(product_id + 1000) * 180
                  END, 2) AS unit_cost,
              -- Price with 30-150% markup
              ROUND(
                  CASE category
                      WHEN 'Electronics' THEN (50 + rand(product_id + 1000) * 450) * (1.3 + rand(product_id + 2000) * 1.2)
                      WHEN 'Clothing' THEN (10 + rand(product_id + 1000) * 90) * (1.3 + rand(product_id + 2000) * 1.2)
                      WHEN 'Home' THEN (20 + rand(product_id + 1000) * 280) * (1.3 + rand(product_id + 2000) * 1.2)
                      WHEN 'Sports' THEN (15 + rand(product_id + 1000) * 135) * (1.3 + rand(product_id + 2000) * 1.2)
                      WHEN 'Office' THEN (5 + rand(product_id + 1000) * 95) * (1.3 + rand(product_id + 2000) * 1.2)
                      ELSE (20 + rand(product_id + 1000) * 180) * (1.3 + rand(product_id + 2000) * 1.2)
                  END, 2) AS unit_price,
              ROUND(0.1 + rand(product_id + 3000) * 24.9, 3) AS weight_kg,
              rand(product_id + 4000) > 0.08 AS is_active,
              date_add('2019-01-01', CAST(rand(product_id + 5000) * 2007 AS INT)) AS launch_date,
              current_timestamp() AS created_at,
              current_timestamp() AS updated_at
          FROM limited_products;
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    Generate Stores:
      type: "sql-executor"
      transitions:
        success:
        - "Verify Data"
      parameters:
        componentName: "Generate Stores"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        enableVariableResolution: "No"
        sqlScript: |
          -- SQL-based Store Data Generator
          -- Generates store/location reference data
          
          INSERT INTO etl_learning.dim_store
          WITH store_data AS (
              SELECT * FROM (VALUES
                  (1, 'STR001', 'Manhattan Flagship', 'Retail', 'New York', 'NY', '10001', 'Northeast', 'John Smith', 15000),
                  (2, 'STR002', 'LA Downtown', 'Retail', 'Los Angeles', 'CA', '90001', 'West', 'Sarah Johnson', 12000),
                  (3, 'STR003', 'Chicago Loop', 'Retail', 'Chicago', 'IL', '60601', 'Midwest', 'Michael Davis', 10000),
                  (4, 'STR004', 'Houston Galleria', 'Retail', 'Houston', 'TX', '77001', 'South', 'Emily Wilson', 11000),
                  (5, 'STR005', 'Phoenix Central', 'Retail', 'Phoenix', 'AZ', '85001', 'Southwest', 'David Brown', 9000),
                  (6, 'STR006', 'Seattle Tech Hub', 'Retail', 'Seattle', 'WA', '98101', 'Northwest', 'Jennifer Martinez', 8500),
                  (7, 'STR007', 'Miami Beach', 'Retail', 'Miami', 'FL', '33101', 'Southeast', 'Robert Taylor', 7500),
                  (8, 'STR008', 'Denver Mile High', 'Retail', 'Denver', 'CO', '80201', 'Mountain', 'Lisa Anderson', 8000),
                  (9, 'STR009', 'East Coast Warehouse', 'Warehouse', 'Newark', 'NJ', '07101', 'Northeast', 'James Thomas', 50000),
                  (10, 'STR010', 'West Coast Warehouse', 'Warehouse', 'Ontario', 'CA', '91761', 'West', 'Michelle Garcia', 60000),
                  (11, 'STR011', 'Central Distribution', 'Warehouse', 'Memphis', 'TN', '38101', 'South', 'William Lee', 55000),
                  (12, 'STR012', 'Online Store', 'Online', 'San Francisco', 'CA', '94101', 'West', 'Jessica White', NULL),
                  (13, 'STR013', 'Mobile App Store', 'Online', 'San Francisco', 'CA', '94101', 'West', 'Daniel Harris', NULL),
                  (14, 'STR014', 'Austin Tech', 'Retail', 'Austin', 'TX', '78701', 'South', 'Amanda Clark', 7000),
                  (15, 'STR015', 'Boston Harbor', 'Retail', 'Boston', 'MA', '02101', 'Northeast', 'Christopher Lewis', 6500)
              ) AS t(store_id, store_code, store_name, store_type, city, state, postal_code, region, manager_name, square_footage)
          )
          SELECT 
              store_id,
              store_code,
              store_name,
              store_type,
              CONCAT(CAST(100 + FLOOR(rand(store_id) * 9900) AS INT), ' Commerce ',
                     CASE CAST(FLOOR(rand(store_id + 100) * 3) AS INT)
                         WHEN 0 THEN 'St'
                         WHEN 1 THEN 'Ave'
                         ELSE 'Blvd'
                     END) AS address_line1,
              city,
              state,
              postal_code,
              'US' AS country,
              region,
              manager_name,
              date_add('2010-01-01', CAST(rand(store_id + 200) * 4000 AS INT)) AS open_date,
              square_footage,
              TRUE AS is_active,
              current_timestamp() AS created_at,
              current_timestamp() AS updated_at
          FROM store_data;
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    Verify Data:
      type: "sql-executor"
      transitions:
        success:
        - "End Success"
      parameters:
        componentName: "Verify Data"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        enableVariableResolution: "No"
        sqlScript: |
          -- Verify product and store data
          SELECT 'dim_product' as table_name, COUNT(*) as record_count FROM etl_learning.dim_product
          UNION ALL
          SELECT 'dim_store', COUNT(*) FROM etl_learning.dim_store;
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"

  variables:
    num_products:
      metadata:
        type: "TEXT"
        description: "Number of products to generate"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "500"

design:
  components:
    Start:
      position:
        x: -400
        "y": 0
      tempMetlId: 1
    Generate Products:
      position:
        x: -250
        "y": 0
      tempMetlId: 2
    Generate Stores:
      position:
        x: -100
        "y": 0
      tempMetlId: 3
    Verify Data:
      position:
        x: 50
        "y": 0
      tempMetlId: 4
    End Success:
      position:
        x: 200
        "y": 0
      tempMetlId: 5
