type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Setup Iteration"
      parameters:
        componentName: "Start"
    
    Setup Iteration:
      type: "python-script"
      transitions:
        success:
        - "Fixed Iterator"
      parameters:
        componentName: "Setup Iteration"
        script: |
          # Demonstrate Fixed Iterator - Processing multiple months
          from datetime import datetime
          
          print('=' * 60)
          print('FIXED ITERATOR DEMONSTRATION')
          print('=' * 60)
          print('This job demonstrates iterating over a fixed set of values')
          print('Processing monthly aggregations for 2024...')
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    Fixed Iterator:
      type: "fixed-iterator"
      transitions:
        success:
        - "Process Month"
      parameters:
        componentName: "Fixed Iterator"
        concurrency: "Sequential"
        variablesToIterate:
        - columnName: "month_value"
          variableName: "current_month"
        iterationValues:
        - - "2024-01"
        - - "2024-02"
        - - "2024-03"
        - - "2024-04"
        - - "2024-05"
        - - "2024-06"
        - - "2024-07"
        - - "2024-08"
        - - "2024-09"
        - - "2024-10"
        - - "2024-11"
        - - "2024-12"
        loggingDetail: "Yes"
        failImmediately: "No"
        breakConditionEnabled: "No"
    
    Process Month:
      type: "sql-executor"
      parameters:
        componentName: "Process Month"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        - "current_month"
        enableVariableResolution: "Yes"
        sqlScript: |
          -- Process monthly sales summary for the current iteration month
          -- Variable ${current_month} is set by the Fixed Iterator
          
          INSERT INTO etl_learning.pipeline_log
          (pipeline_name, step_name, status, message, records_processed, execution_timestamp)
          SELECT
              '10_iterator_fixed_demo',
              'Process Month: ${current_month}',
              'SUCCESS',
              'Monthly aggregation completed',
              COUNT(*),
              current_timestamp()
          FROM etl_learning.fact_sales
          WHERE year_month = '${current_month}';
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    Log Completion:
      type: "python-script"
      transitions:
        success:
        - "End Success"
      parameters:
        componentName: "Log Completion"
        script: |
          from datetime import datetime
          
          print('=' * 60)
          print('Fixed Iterator completed successfully!')
          print(f'Processed 12 months of data')
          print(f'Completed: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
          print('=' * 60)
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"

  variables:
    current_month:
      metadata:
        type: "TEXT"
        description: "Current month being processed by iterator"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "2024-01"

design:
  components:
    Start:
      position:
        x: -400
        "y": 0
      tempMetlId: 1
    Setup Iteration:
      position:
        x: -250
        "y": 0
      tempMetlId: 2
    Fixed Iterator:
      position:
        x: -100
        "y": 0
      tempMetlId: 3
    Process Month:
      position:
        x: 50
        "y": 0
      tempMetlId: 4
    Log Completion:
      position:
        x: 200
        "y": 0
      tempMetlId: 5
    End Success:
      position:
        x: 350
        "y": 0
      tempMetlId: 6
